using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class watScript : MonoBehaviour
{
    private int number=0;
    [SerializeField] private TextMeshProUGUI Word;
    private int WordCount =0;
    private bool firstCheck;
    [SerializeField] private GameObject MenuPanel;

    private string[] WatList = new string[] {"HONEST","AFRAID","EXCEL","REVOLT","THIEF","SPORTSMAN","IMPROVE","DIRTY","OBSCURE","BOLD","PUNISHMENT","HOSPITAL","CHARMING","JUMP","TIME","PRETEST","ALARM","AHEAD","STAMINA","TERRORIST","EXAM","PROGRESS","DOCTOR","SURPRISE","GRASS","BORROW","LIES","CROWD","LIBERTY","INVOLVE","DESPEND","COMPLEX","MASTER","BOX","ARRANGEMENT","ENEMY","MOOD","IMITATIVE","NEGLECT","ATTENTIVE","DULL","MINIMUM","INJUSTICE","FOLLOW","ENFORCE","RING","FIX","BARRIER","EXCEPT","INSIGHT","SYMPATHY","TRAVEL","HUNTING","HAND","HAST","HELPLESS","EAT","HOUSE","FREEDOM","WELCOME","MISUNDERSTANDING","NATURE","REJECT","MAN","PRECAUTION","TAUGHT","SATISFACTION","LOAN","CHEAT","UNDERSTAND","LAUGHING","MERIT","MOBILE","GREEDY","MEDICINE","HEAT","MOVEMENT","MANNER","PARK","COMMAND","SCARED","DEVELOP","POETRY","CATCH","BLIND","LAST","WRONG","ACTION","SCAN","THREAT","WEEP","ABSOLUTE","TEAMSPIRIT","FLOW","MOVE","WATCH","FRIENDSHIP","SMART","SPACESHIPS","SPEAK","NATION","OBTAIN","CLAIM","DANGER","SHIP","SUPPOSE","TIREDNESS","TEMPER","FIRST","ENERGY","DIFFICULT","PULL","TORTURE","JOURNAL","APT","ALL","CREATE","OPEN","STOP","PEACE","RESPONSE","PRINCIPLE","PUSH","CALL","IMPRESS","PITY","DRIVE","VANITY","FAILURE","PROMOTE","FILMS","ALERT","ATTENTION","AMBASSADOR","TERM","HEALTH","FRIEND","CROOK","SINCERITY","HEIGHT","RESTORE","GARDEN","DISCIPLINE","DIRECT","POINT","BULLET","DELIGHT","DEFEND","BOON","MORAL","TIE","CONDEMN","GUARD","DETAIL","FEARFULNESS","FALSE","STEP","OPERATION","HUMANITY","WORSE","RESULT","DEATH","FLEXIBILITY","TALK","FURTHER","EDUCATE","BILATERAL","AFFECTION","RELIGION","COMPROMISE","CONFERENCE","FIRE","CLEVER","BUSY","DENY","HIJACK","OFFENCE","CUSTOM","MALE","ABLE","BREAD","SELFISH","MAKE","PROJECT","FREEDOM","POVERTY","WORK","RECOMMEND","REGULAR","LOYAL","SAVE","ATTACHMENT","CLIMATE","AGONY","REST","DWARF","BOREDOM","MAP","SHAME","QUEST","NIGHT","SATISFY","FIT","INTERRUPT","MOTIVATED","PISTOL","DUMMY","WITHDRAW","SINCERE","BALANCE","COMMANDER","CONQUER","EARN","BOOK","LEARNED","ANSWER","REPRESENT","PAST","ASSUME","HESITATION","TEST","COMPANY","HEADMASTER","LAIN","PAY","COPY","COMPLETE","MODERN","PROCESS","INTERPRETATION","HUNGRY","MORNING","MACHINE","VICTORY","RAIN","FAMOUS","KILLER","MINISTER","DEDICATE","STONE","CONSOLE","WOMEN","LOGIC","SUBMIT","FELLOW","NEGLIGIBLE","GEM","CONSCIENCE","MILK","SHOUT","MISS","ENCOURAGE","GOON","LOSE","CHARI","DONATION","KEEN","VALUABLE","RECOGNIZE","ENTER","INSPECTION","NEED","ALWAYS","TOUGH","ACCEPT","LONELY","HURRY","SIGN","RACE","AVOID","SPORTS","HARBOUR","FAVOUR","INNOVATION","FOOL","DICTATORSHIP","SHORT","LOVELY","SORROW","LEVEL","PRESSURE","SAME","URGE","FILLED","NATIVE","BILL","GREAT","MISER","CULPRIT","ATTITUDE","DIVERSITY","MISERY","DISAGREE","PRESS","ATTRACT","PATRIOTISM","DESIGNATION","PATRIOT","PILL","DACOIT","DIE","COUNTRY","CANCEL","SCREEN","FIRM","BACHELOR","SPEND","PUNISH","SPIRIT","ABRUPT"};
    // Start is called before the first frame update
    void Start()
    { 
       number =  Random.Range(0,WatList.Length);
       Word.text = WatList[number];
       StartCoroutine(WatRead());
    }

    // Update is called once per frame
    void Update()
    {

    }

    IEnumerator WatRead()
    {
      WordCount +=1;
     if(WordCount>=61)
     {
      Word.text = "WAT-Done";
      yield return new WaitForSeconds(2.0f);
      MenuPanel.SetActive(true);
      gameObject.SetActive(false);
     }
     else
     {
      yield return new WaitForSeconds(.25f);
      number =  Random.Range(0,WatList.Length);
      Word.text = WatList[number];
      StartCoroutine(WatRead());
     }
    }
}
